name = "botw"
main = "src/index.js"
compatibility_date = "2026-01-01"

# The database is created by `wrangler d1 create botw`, which prints the id to paste in here.
[[d1_databases]]
binding = "DB"
database_name = "botw"
database_id = "paste-the-id-wrangler-prints-here"
